# Latest version, recommended
version: 2

# Default only builds HTML
formats: []

# Install via pip/poetry and docs requirements
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt

# Use python 3.10
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Fail on warnings to ensure build render properly
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
