# Latest version, recommended
version: 2

# Default only builds HTML
formats: []

# Install via pip/poetry and docs requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Use python 3.9
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Do not fail because of warnings on type hinting
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
