# Latest version, recommended
version: 2

# Default only builds HTML
formats: []

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
