openapi: 3.0.0

info:
  title: TrainingSet API
  description: XXX TODO
  version: 0.1.9

paths:
  /find:
    post:
      summary: List TrainingSet
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            format: int64
          description: Number of items to skip
        - in: query
          name: limit
          schema:
            type: integer
            format: int64
          description: Number of items to return
        - in: query
          name: asc
          schema:
            type: boolean
          description: Sort order
      requestBody:
        description: Search filter
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingSetFilter'
      responses:
        '200':
          description: The TrainingSet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrainingSet'

  /{trainingSetName}:
    get:
      summary: Get TrainingSet
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
      responses:
        '200':
          description: The TrainingSet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSet'
    post:
      summary: Create TrainingSetVersion
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
      requestBody:
        description: CreateTrainingSetVersionRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrainingSetVersionRequest'
      responses:
        '200':
          description: The new TrainingSetVersion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSetVersion'
    put:
      summary: Update TrainingSet
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
      requestBody:
        description: UpdateTrainingSetRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTrainingSetRequest'
      responses:
        '200':
          description: Updated TrainingSet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSet'

  /{trainingSetName}/{number}:
    get:
      summary: Get TrainingSetVersion
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
        - in: path
          name: number
          required: true
          schema:
            type: integer
            minimum: 1
          description: The TrainingSetVersion number
      responses:
        '200':
          description: The new TrainingSetVersion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSetVersion'
    put:
      summary: Update TrainingSetVersion
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
        - in: path
          name: number
          required: true
          schema:
            type: integer
            minimum: 1
          description: The TrainingSetVersion number
      requestBody:
        description: UpdateTrainingSetVersionRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTrainingSetVersionRequest'
      responses:
        '200':
          description: Updated TrainingSetVersion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSetVersion'

components:
  schemas:
    TrainingSet:
      type: object
      properties:
        id:
          type: string
        projectId:
          type: string
        name:
          type: string
        description:
          type: string
        creationTime:
          type: string
          format: date-time
        ownerId:
          type: string
        ownerName:
          type: string
        collaboratorIds:
          type: array
          items:
            type: string
        collaboratorNames:
          type: array
          items:
            type: string
        meta:
          type: object
          additionalProperties:
            type: string
      required:
        - creationTime
        - collaboratorIds
        - collaboratorNames
        - id
        - meta
        - name
        - ownerId
        - ownerName
        - projectId
    UpdateTrainingSetRequest:
      type: object
      properties:
        description:
          type: string
        ownerName:
          type: string
        collaboratorNames:
          type: array
          items:
            type: string
        meta:
          type: object
          additionalProperties:
            type: string
      required:
        - collaboratorNames
        - meta
        - ownerName
    CreateTrainingSetVersionRequest:
      type: object
      properties:
        projectOwnerUsername:
          type: string
        projectName:
          type: string
        keyColumns:
          type: array
          items:
            type: string
        targetColumns:
          type: array
          items:
            type: string
        excludeColumns:
          type: array
          items:
            type: string
        monitoringMeta:
          $ref: '#/components/schemas/MonitoringMeta'
        name:
          type: string
        description:
          type: string
        meta:
          type: object
          additionalProperties:
            type: string
      required:
        - excludeColumns
        - keyColumns
        - meta
        - monitoringMeta
        - projectName
        - projectOwnerUsername
        - targetColumns
    TrainingSetVersion:
      type: object
      properties:
        id:
          type: string
        trainingSetId:
          type: string
        trainingSetName:
          type: string
        number:
          type: integer
        creationTime:
          type: string
          format: date-time
        url:
          description: url in object store (e.g. an s3 url)
          type: string
        keyColumns:
          type: array
          items:
            type: string
        targetColumns:
          type: array
          items:
            type: string
        excludeColumns:
          type: array
          items:
            type: string
        monitoringMeta:
          $ref: '#/components/schemas/MonitoringMeta'
        description:
          type: string
        meta:
          type: object
          additionalProperties:
            type: string
        pending:
          type: boolean
      required:
        - creationTime
        - excludeColumns
        - id
        - keyColumns
        - meta
        - monitoringMeta
        - number
        - pending
        - targetColumns
        - trainingSetId
        - trainingSetName
        - url
    UpdateTrainingSetVersionRequest:
      type: object
      properties:
        keyColumns:
          type: array
          items:
            type: string
        targetColumns:
          type: array
          items:
            type: string
        excludeColumns:
          type: array
          items:
            type: string
        monitoringMeta:
          $ref: '#/components/schemas/MonitoringMeta'
        description:
          type: string
        meta:
          type: object
          additionalProperties:
            type: string
        pending:
          type: boolean
      required:
        - excludeColumns
        - keyColumns
        - meta
        - monitoringMeta
        - pending
        - targetColumns
    MonitoringMeta:
      type: object
      properties:
        timestampColumns:
           type: array
           items:
             type: string
        categoricalColumns:
          type: array
          items:
            type: string
        ordinalColumns:
          type: array
          items:
            type: string
      required:
        - categoricalColumns
        - ordinalColumns
        - timestampColumns
    TrainingSetVersionUrl:
      type: object
      properties:
        trainingSetVersionId:
          type: string
        url:
          type: string
      required:
        - trainingSetVersionId
        - url
    TrainingSetFilter:
      type: object
      properties:
        projectName:
          type: string
        ownerName:
          type: string
        meta:
          type: object
          additionalProperties:
            type: string
