openapi: 3.0.0

info:
  title: TrainingSet API
  description: XXX TODO
  version: 0.1.9

paths:
  /{trainingSetName}/version:
    post:
      summary: Create TrainingSetVersion
      parameters:
        - in: path
          name: trainingSetName
          required: true
          schema:
            type: string
            minimum: 1
          description: The TrainingSet name
      requestBody:
        description: CreateTrainingSetVersionRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrainingSetVersionRequest'
      responses:
        '200':
          description: The new TrainingSetVersion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrainingSetVersion'

components:
  schemas:
    TrainingSet:
      type: object
      properties:
        id:
          type: string
        projectId:
          type: string
        name:
          type: string
        description:
          type: string
        creationTime:
          type: string
          format: date-time
        ownerId:
          type: string
        # XXX TODO ACL
        metadata:
          type: object
          additionalProperties:
            type: string
      required:
        - creationTime
        - id
        - metadata
        - name
        - ownerId
        - projectId
    CreateTrainingSetVersionRequest:
      type: object
      properties:
        projectOwnerUsername:
          type: string
        projectName:
          type: string
        timestampColumn:
          type: string
        independentVars:
          type: array
          items:
            type: string
        targetVars:
          type: array
          items:
            type: string
        continuousVars:
          type: array
          items:
            type: string
        categoricalVars:
          type: array
          items:
            type: string
        ordinalVars:
          type: array
          items:
            type: string
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string
      required:
        - categoricalVars
        - continuousVars
        - independentVars
        - metadata
        - ordinalVars
        - projectName
        - projectOwnerUsername
        - targetVars
        - timestampColumn
    UpdateTrainingSetVersionRequest:
      type: object
      properties:
        pending:
          type: boolean
    TrainingSetVersion:
      type: object
      properties:
        id:
          type: string
        trainingSetId:
          type: string
        creationTime:
          type: string
          format: date-time
        url:
          description: url in object store (e.g. an s3 url)
          type: string
        timestampColumn:
          type: string
        independentVars:
          type: array
          items:
            type: string
        targetVars:
          type: array
          items:
            type: string
        continuousVars:
          type: array
          items:
            type: string
        categoricalVars:
          type: array
          items:
            type: string
        ordinalVars:
          type: array
          items:
            type: string
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string
        pending:
          type: boolean
      required:
        - categoricalVars
        - continuousVars
        - creationTime
        - id
        - independentVars
        - metadata
        - pending
        - ordinalVars
        - targetVars
        - timestampColumn
        - trainingSetId
        - url
    TrainingSetVersionUrl:
      type: object
      properties:
        trainingSetVersionId:
          type: string
        url:
          type: string
      required:
        - trainingSetVersionId
        - url
