# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RemotefsProject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "added_at": "str",
        "added_by": "RemotefsUserSummary",
        "name": "str",
        "project_id": "str",
        "volume_id": "str",
    }

    attribute_map = {
        "added_at": "addedAt",
        "added_by": "addedBy",
        "name": "name",
        "project_id": "projectId",
        "volume_id": "volumeId",
    }

    def __init__(
        self, added_at=None, added_by=None, name=None, project_id=None, volume_id=None
    ):  # noqa: E501
        """RemotefsProject - a model defined in Swagger"""  # noqa: E501
        self._added_at = None
        self._added_by = None
        self._name = None
        self._project_id = None
        self._volume_id = None
        self.discriminator = None
        self.added_at = added_at
        self.added_by = added_by
        self.name = name
        self.project_id = project_id
        self.volume_id = volume_id

    @property
    def added_at(self):
        """Gets the added_at of this RemotefsProject.  # noqa: E501


        :return: The added_at of this RemotefsProject.  # noqa: E501
        :rtype: str
        """
        return self._added_at

    @added_at.setter
    def added_at(self, added_at):
        """Sets the added_at of this RemotefsProject.


        :param added_at: The added_at of this RemotefsProject.  # noqa: E501
        :type: str
        """
        if added_at is None:
            raise ValueError("Invalid value for `added_at`, must not be `None`")  # noqa: E501

        self._added_at = added_at

    @property
    def added_by(self):
        """Gets the added_by of this RemotefsProject.  # noqa: E501


        :return: The added_by of this RemotefsProject.  # noqa: E501
        :rtype: RemotefsUserSummary
        """
        return self._added_by

    @added_by.setter
    def added_by(self, added_by):
        """Sets the added_by of this RemotefsProject.


        :param added_by: The added_by of this RemotefsProject.  # noqa: E501
        :type: RemotefsUserSummary
        """
        if added_by is None:
            raise ValueError("Invalid value for `added_by`, must not be `None`")  # noqa: E501

        self._added_by = added_by

    @property
    def name(self):
        """Gets the name of this RemotefsProject.  # noqa: E501


        :return: The name of this RemotefsProject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RemotefsProject.


        :param name: The name of this RemotefsProject.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this RemotefsProject.  # noqa: E501

        References Mongo project ID  # noqa: E501

        :return: The project_id of this RemotefsProject.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this RemotefsProject.

        References Mongo project ID  # noqa: E501

        :param project_id: The project_id of this RemotefsProject.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def volume_id(self):
        """Gets the volume_id of this RemotefsProject.  # noqa: E501


        :return: The volume_id of this RemotefsProject.  # noqa: E501
        :rtype: str
        """
        return self._volume_id

    @volume_id.setter
    def volume_id(self, volume_id):
        """Sets the volume_id of this RemotefsProject.


        :param volume_id: The volume_id of this RemotefsProject.  # noqa: E501
        :type: str
        """
        if volume_id is None:
            raise ValueError("Invalid value for `volume_id`, must not be `None`")  # noqa: E501

        self._volume_id = volume_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RemotefsProject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemotefsProject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
