# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RemotefsDataTransfer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "created_at": "str",
        "created_by": "RemotefsUserSummary",
        "destination_volume_id": "str",
        "filetask_key": "str",
        "id": "str",
        "labels": "dict(str, str)",
        "status": "RemotefsDataTransferStatus",
        "task_update": "RemotefsTaskUpdate",
        "type": "RemotefsDataTransferType",
        "updated_at": "str",
        "updated_by": "RemotefsUserSummary",
    }

    attribute_map = {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "destination_volume_id": "destinationVolumeId",
        "filetask_key": "filetaskKey",
        "id": "id",
        "labels": "labels",
        "status": "status",
        "task_update": "taskUpdate",
        "type": "type",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    }

    def __init__(
        self,
        created_at=None,
        created_by=None,
        destination_volume_id=None,
        filetask_key=None,
        id=None,
        labels=None,
        status=None,
        task_update=None,
        type=None,
        updated_at=None,
        updated_by=None,
    ):  # noqa: E501
        """RemotefsDataTransfer - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._created_by = None
        self._destination_volume_id = None
        self._filetask_key = None
        self._id = None
        self._labels = None
        self._status = None
        self._task_update = None
        self._type = None
        self._updated_at = None
        self._updated_by = None
        self.discriminator = None
        self.created_at = created_at
        self.created_by = created_by
        self.destination_volume_id = destination_volume_id
        if filetask_key is not None:
            self.filetask_key = filetask_key
        self.id = id
        if labels is not None:
            self.labels = labels
        self.status = status
        if task_update is not None:
            self.task_update = task_update
        self.type = type
        self.updated_at = updated_at
        self.updated_by = updated_by

    @property
    def created_at(self):
        """Gets the created_at of this RemotefsDataTransfer.  # noqa: E501


        :return: The created_at of this RemotefsDataTransfer.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this RemotefsDataTransfer.


        :param created_at: The created_at of this RemotefsDataTransfer.  # noqa: E501
        :type: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this RemotefsDataTransfer.  # noqa: E501


        :return: The created_by of this RemotefsDataTransfer.  # noqa: E501
        :rtype: RemotefsUserSummary
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this RemotefsDataTransfer.


        :param created_by: The created_by of this RemotefsDataTransfer.  # noqa: E501
        :type: RemotefsUserSummary
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def destination_volume_id(self):
        """Gets the destination_volume_id of this RemotefsDataTransfer.  # noqa: E501


        :return: The destination_volume_id of this RemotefsDataTransfer.  # noqa: E501
        :rtype: str
        """
        return self._destination_volume_id

    @destination_volume_id.setter
    def destination_volume_id(self, destination_volume_id):
        """Sets the destination_volume_id of this RemotefsDataTransfer.


        :param destination_volume_id: The destination_volume_id of this RemotefsDataTransfer.  # noqa: E501
        :type: str
        """
        if destination_volume_id is None:
            raise ValueError(
                "Invalid value for `destination_volume_id`, must not be `None`"
            )  # noqa: E501

        self._destination_volume_id = destination_volume_id

    @property
    def filetask_key(self):
        """Gets the filetask_key of this RemotefsDataTransfer.  # noqa: E501


        :return: The filetask_key of this RemotefsDataTransfer.  # noqa: E501
        :rtype: str
        """
        return self._filetask_key

    @filetask_key.setter
    def filetask_key(self, filetask_key):
        """Sets the filetask_key of this RemotefsDataTransfer.


        :param filetask_key: The filetask_key of this RemotefsDataTransfer.  # noqa: E501
        :type: str
        """

        self._filetask_key = filetask_key

    @property
    def id(self):
        """Gets the id of this RemotefsDataTransfer.  # noqa: E501


        :return: The id of this RemotefsDataTransfer.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RemotefsDataTransfer.


        :param id: The id of this RemotefsDataTransfer.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def labels(self):
        """Gets the labels of this RemotefsDataTransfer.  # noqa: E501


        :return: The labels of this RemotefsDataTransfer.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this RemotefsDataTransfer.


        :param labels: The labels of this RemotefsDataTransfer.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels = labels

    @property
    def status(self):
        """Gets the status of this RemotefsDataTransfer.  # noqa: E501


        :return: The status of this RemotefsDataTransfer.  # noqa: E501
        :rtype: RemotefsDataTransferStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RemotefsDataTransfer.


        :param status: The status of this RemotefsDataTransfer.  # noqa: E501
        :type: RemotefsDataTransferStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def task_update(self):
        """Gets the task_update of this RemotefsDataTransfer.  # noqa: E501


        :return: The task_update of this RemotefsDataTransfer.  # noqa: E501
        :rtype: RemotefsTaskUpdate
        """
        return self._task_update

    @task_update.setter
    def task_update(self, task_update):
        """Sets the task_update of this RemotefsDataTransfer.


        :param task_update: The task_update of this RemotefsDataTransfer.  # noqa: E501
        :type: RemotefsTaskUpdate
        """

        self._task_update = task_update

    @property
    def type(self):
        """Gets the type of this RemotefsDataTransfer.  # noqa: E501


        :return: The type of this RemotefsDataTransfer.  # noqa: E501
        :rtype: RemotefsDataTransferType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RemotefsDataTransfer.


        :param type: The type of this RemotefsDataTransfer.  # noqa: E501
        :type: RemotefsDataTransferType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def updated_at(self):
        """Gets the updated_at of this RemotefsDataTransfer.  # noqa: E501


        :return: The updated_at of this RemotefsDataTransfer.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this RemotefsDataTransfer.


        :param updated_at: The updated_at of this RemotefsDataTransfer.  # noqa: E501
        :type: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def updated_by(self):
        """Gets the updated_by of this RemotefsDataTransfer.  # noqa: E501


        :return: The updated_by of this RemotefsDataTransfer.  # noqa: E501
        :rtype: RemotefsUserSummary
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this RemotefsDataTransfer.


        :param updated_by: The updated_by of this RemotefsDataTransfer.  # noqa: E501
        :type: RemotefsUserSummary
        """
        if updated_by is None:
            raise ValueError("Invalid value for `updated_by`, must not be `None`")  # noqa: E501

        self._updated_by = updated_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RemotefsDataTransfer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemotefsDataTransfer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
