# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RemotefsFilesystem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "created_at": "str",
        "created_by": "RemotefsUserSummary",
        "data_plane_id": "str",
        "data_plane_name": "str",
        "hostname": "str",
        "id": "str",
        "is_data_plane_default": "bool",
        "max_snapshots_per_volume": "int",
        "name": "str",
        "num_volumes": "int",
        "root_pvc": "str",
        "storage_class": "str",
        "updated_at": "str",
        "updated_by": "RemotefsUserSummary",
    }

    attribute_map = {
        "created_at": "createdAt",
        "created_by": "createdBy",
        "data_plane_id": "dataPlaneId",
        "data_plane_name": "dataPlaneName",
        "hostname": "hostname",
        "id": "id",
        "is_data_plane_default": "isDataPlaneDefault",
        "max_snapshots_per_volume": "maxSnapshotsPerVolume",
        "name": "name",
        "num_volumes": "numVolumes",
        "root_pvc": "rootPvc",
        "storage_class": "storageClass",
        "updated_at": "updatedAt",
        "updated_by": "updatedBy",
    }

    def __init__(
        self,
        created_at=None,
        created_by=None,
        data_plane_id=None,
        data_plane_name=None,
        hostname=None,
        id=None,
        is_data_plane_default=None,
        max_snapshots_per_volume=None,
        name=None,
        num_volumes=None,
        root_pvc=None,
        storage_class=None,
        updated_at=None,
        updated_by=None,
    ):  # noqa: E501
        """RemotefsFilesystem - a model defined in Swagger"""  # noqa: E501
        self._created_at = None
        self._created_by = None
        self._data_plane_id = None
        self._data_plane_name = None
        self._hostname = None
        self._id = None
        self._is_data_plane_default = None
        self._max_snapshots_per_volume = None
        self._name = None
        self._num_volumes = None
        self._root_pvc = None
        self._storage_class = None
        self._updated_at = None
        self._updated_by = None
        self.discriminator = None
        self.created_at = created_at
        self.created_by = created_by
        self.data_plane_id = data_plane_id
        self.data_plane_name = data_plane_name
        if hostname is not None:
            self.hostname = hostname
        self.id = id
        self.is_data_plane_default = is_data_plane_default
        self.max_snapshots_per_volume = max_snapshots_per_volume
        self.name = name
        if num_volumes is not None:
            self.num_volumes = num_volumes
        self.root_pvc = root_pvc
        self.storage_class = storage_class
        self.updated_at = updated_at
        self.updated_by = updated_by

    @property
    def created_at(self):
        """Gets the created_at of this RemotefsFilesystem.  # noqa: E501


        :return: The created_at of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this RemotefsFilesystem.


        :param created_at: The created_at of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this RemotefsFilesystem.  # noqa: E501


        :return: The created_by of this RemotefsFilesystem.  # noqa: E501
        :rtype: RemotefsUserSummary
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this RemotefsFilesystem.


        :param created_by: The created_by of this RemotefsFilesystem.  # noqa: E501
        :type: RemotefsUserSummary
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def data_plane_id(self):
        """Gets the data_plane_id of this RemotefsFilesystem.  # noqa: E501


        :return: The data_plane_id of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._data_plane_id

    @data_plane_id.setter
    def data_plane_id(self, data_plane_id):
        """Sets the data_plane_id of this RemotefsFilesystem.


        :param data_plane_id: The data_plane_id of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if data_plane_id is None:
            raise ValueError("Invalid value for `data_plane_id`, must not be `None`")  # noqa: E501

        self._data_plane_id = data_plane_id

    @property
    def data_plane_name(self):
        """Gets the data_plane_name of this RemotefsFilesystem.  # noqa: E501


        :return: The data_plane_name of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._data_plane_name

    @data_plane_name.setter
    def data_plane_name(self, data_plane_name):
        """Sets the data_plane_name of this RemotefsFilesystem.


        :param data_plane_name: The data_plane_name of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if data_plane_name is None:
            raise ValueError(
                "Invalid value for `data_plane_name`, must not be `None`"
            )  # noqa: E501

        self._data_plane_name = data_plane_name

    @property
    def hostname(self):
        """Gets the hostname of this RemotefsFilesystem.  # noqa: E501

        Data plane prefix (e.g. mydp1029), \"\" for local data plane  # noqa: E501

        :return: The hostname of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this RemotefsFilesystem.

        Data plane prefix (e.g. mydp1029), \"\" for local data plane  # noqa: E501

        :param hostname: The hostname of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def id(self):
        """Gets the id of this RemotefsFilesystem.  # noqa: E501


        :return: The id of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RemotefsFilesystem.


        :param id: The id of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def is_data_plane_default(self):
        """Gets the is_data_plane_default of this RemotefsFilesystem.  # noqa: E501


        :return: The is_data_plane_default of this RemotefsFilesystem.  # noqa: E501
        :rtype: bool
        """
        return self._is_data_plane_default

    @is_data_plane_default.setter
    def is_data_plane_default(self, is_data_plane_default):
        """Sets the is_data_plane_default of this RemotefsFilesystem.


        :param is_data_plane_default: The is_data_plane_default of this RemotefsFilesystem.  # noqa: E501
        :type: bool
        """
        if is_data_plane_default is None:
            raise ValueError(
                "Invalid value for `is_data_plane_default`, must not be `None`"
            )  # noqa: E501

        self._is_data_plane_default = is_data_plane_default

    @property
    def max_snapshots_per_volume(self):
        """Gets the max_snapshots_per_volume of this RemotefsFilesystem.  # noqa: E501


        :return: The max_snapshots_per_volume of this RemotefsFilesystem.  # noqa: E501
        :rtype: int
        """
        return self._max_snapshots_per_volume

    @max_snapshots_per_volume.setter
    def max_snapshots_per_volume(self, max_snapshots_per_volume):
        """Sets the max_snapshots_per_volume of this RemotefsFilesystem.


        :param max_snapshots_per_volume: The max_snapshots_per_volume of this RemotefsFilesystem.  # noqa: E501
        :type: int
        """
        if max_snapshots_per_volume is None:
            raise ValueError(
                "Invalid value for `max_snapshots_per_volume`, must not be `None`"
            )  # noqa: E501

        self._max_snapshots_per_volume = max_snapshots_per_volume

    @property
    def name(self):
        """Gets the name of this RemotefsFilesystem.  # noqa: E501


        :return: The name of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RemotefsFilesystem.


        :param name: The name of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def num_volumes(self):
        """Gets the num_volumes of this RemotefsFilesystem.  # noqa: E501


        :return: The num_volumes of this RemotefsFilesystem.  # noqa: E501
        :rtype: int
        """
        return self._num_volumes

    @num_volumes.setter
    def num_volumes(self, num_volumes):
        """Sets the num_volumes of this RemotefsFilesystem.


        :param num_volumes: The num_volumes of this RemotefsFilesystem.  # noqa: E501
        :type: int
        """

        self._num_volumes = num_volumes

    @property
    def root_pvc(self):
        """Gets the root_pvc of this RemotefsFilesystem.  # noqa: E501


        :return: The root_pvc of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._root_pvc

    @root_pvc.setter
    def root_pvc(self, root_pvc):
        """Sets the root_pvc of this RemotefsFilesystem.


        :param root_pvc: The root_pvc of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if root_pvc is None:
            raise ValueError("Invalid value for `root_pvc`, must not be `None`")  # noqa: E501

        self._root_pvc = root_pvc

    @property
    def storage_class(self):
        """Gets the storage_class of this RemotefsFilesystem.  # noqa: E501


        :return: The storage_class of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._storage_class

    @storage_class.setter
    def storage_class(self, storage_class):
        """Sets the storage_class of this RemotefsFilesystem.


        :param storage_class: The storage_class of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if storage_class is None:
            raise ValueError("Invalid value for `storage_class`, must not be `None`")  # noqa: E501

        self._storage_class = storage_class

    @property
    def updated_at(self):
        """Gets the updated_at of this RemotefsFilesystem.  # noqa: E501


        :return: The updated_at of this RemotefsFilesystem.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this RemotefsFilesystem.


        :param updated_at: The updated_at of this RemotefsFilesystem.  # noqa: E501
        :type: str
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def updated_by(self):
        """Gets the updated_by of this RemotefsFilesystem.  # noqa: E501


        :return: The updated_by of this RemotefsFilesystem.  # noqa: E501
        :rtype: RemotefsUserSummary
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this RemotefsFilesystem.


        :param updated_by: The updated_by of this RemotefsFilesystem.  # noqa: E501
        :type: RemotefsUserSummary
        """
        if updated_by is None:
            raise ValueError("Invalid value for `updated_by`, must not be `None`")  # noqa: E501

        self._updated_by = updated_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RemotefsFilesystem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemotefsFilesystem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
