# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class RemotefsFlowsArtifactVersionKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"artifact_id": "str", "execution": "RemotefsFlowsExecutionIdentifier"}

    attribute_map = {"artifact_id": "artifactId", "execution": "execution"}

    def __init__(self, artifact_id=None, execution=None):  # noqa: E501
        """RemotefsFlowsArtifactVersionKey - a model defined in Swagger"""  # noqa: E501
        self._artifact_id = None
        self._execution = None
        self.discriminator = None
        if artifact_id is not None:
            self.artifact_id = artifact_id
        if execution is not None:
            self.execution = execution

    @property
    def artifact_id(self):
        """Gets the artifact_id of this RemotefsFlowsArtifactVersionKey.  # noqa: E501


        :return: The artifact_id of this RemotefsFlowsArtifactVersionKey.  # noqa: E501
        :rtype: str
        """
        return self._artifact_id

    @artifact_id.setter
    def artifact_id(self, artifact_id):
        """Sets the artifact_id of this RemotefsFlowsArtifactVersionKey.


        :param artifact_id: The artifact_id of this RemotefsFlowsArtifactVersionKey.  # noqa: E501
        :type: str
        """

        self._artifact_id = artifact_id

    @property
    def execution(self):
        """Gets the execution of this RemotefsFlowsArtifactVersionKey.  # noqa: E501


        :return: The execution of this RemotefsFlowsArtifactVersionKey.  # noqa: E501
        :rtype: RemotefsFlowsExecutionIdentifier
        """
        return self._execution

    @execution.setter
    def execution(self, execution):
        """Sets the execution of this RemotefsFlowsArtifactVersionKey.


        :param execution: The execution of this RemotefsFlowsArtifactVersionKey.  # noqa: E501
        :type: RemotefsFlowsExecutionIdentifier
        """

        self._execution = execution

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(RemotefsFlowsArtifactVersionKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemotefsFlowsArtifactVersionKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
