# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServerVolumePermissionsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"must_have": "list[RemotefsPermission]", "principal": "ServerPrincipal"}

    attribute_map = {"must_have": "mustHave", "principal": "principal"}

    def __init__(self, must_have=None, principal=None):  # noqa: E501
        """ServerVolumePermissionsRequest - a model defined in Swagger"""  # noqa: E501
        self._must_have = None
        self._principal = None
        self.discriminator = None
        self.must_have = must_have
        self.principal = principal

    @property
    def must_have(self):
        """Gets the must_have of this ServerVolumePermissionsRequest.  # noqa: E501


        :return: The must_have of this ServerVolumePermissionsRequest.  # noqa: E501
        :rtype: list[RemotefsPermission]
        """
        return self._must_have

    @must_have.setter
    def must_have(self, must_have):
        """Sets the must_have of this ServerVolumePermissionsRequest.


        :param must_have: The must_have of this ServerVolumePermissionsRequest.  # noqa: E501
        :type: list[RemotefsPermission]
        """
        if must_have is None:
            raise ValueError("Invalid value for `must_have`, must not be `None`")  # noqa: E501

        self._must_have = must_have

    @property
    def principal(self):
        """Gets the principal of this ServerVolumePermissionsRequest.  # noqa: E501


        :return: The principal of this ServerVolumePermissionsRequest.  # noqa: E501
        :rtype: ServerPrincipal
        """
        return self._principal

    @principal.setter
    def principal(self, principal):
        """Sets the principal of this ServerVolumePermissionsRequest.


        :param principal: The principal of this ServerVolumePermissionsRequest.  # noqa: E501
        :type: ServerPrincipal
        """
        if principal is None:
            raise ValueError("Invalid value for `principal`, must not be `None`")  # noqa: E501

        self._principal = principal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ServerVolumePermissionsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerVolumePermissionsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
