# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServerPermissionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "code": "RemotefsPermissionCode",
        "context": "ServerPermissionInfoContext",
        "id": "str",
    }

    attribute_map = {"code": "code", "context": "context", "id": "id"}

    def __init__(self, code=None, context=None, id=None):  # noqa: E501
        """ServerPermissionInfo - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._context = None
        self._id = None
        self.discriminator = None
        self.code = code
        self.context = context
        self.id = id

    @property
    def code(self):
        """Gets the code of this ServerPermissionInfo.  # noqa: E501


        :return: The code of this ServerPermissionInfo.  # noqa: E501
        :rtype: RemotefsPermissionCode
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ServerPermissionInfo.


        :param code: The code of this ServerPermissionInfo.  # noqa: E501
        :type: RemotefsPermissionCode
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def context(self):
        """Gets the context of this ServerPermissionInfo.  # noqa: E501


        :return: The context of this ServerPermissionInfo.  # noqa: E501
        :rtype: ServerPermissionInfoContext
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this ServerPermissionInfo.


        :param context: The context of this ServerPermissionInfo.  # noqa: E501
        :type: ServerPermissionInfoContext
        """
        if context is None:
            raise ValueError("Invalid value for `context`, must not be `None`")  # noqa: E501

        self._context = context

    @property
    def id(self):
        """Gets the id of this ServerPermissionInfo.  # noqa: E501


        :return: The id of this ServerPermissionInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServerPermissionInfo.


        :param id: The id of this ServerPermissionInfo.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ServerPermissionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerPermissionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
