# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServerCreateSnapshotFromRun(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"description": "str", "run_id": "str", "user_id": "str", "volume_id": "str"}

    attribute_map = {
        "description": "description",
        "run_id": "runId",
        "user_id": "userId",
        "volume_id": "volumeId",
    }

    def __init__(self, description=None, run_id=None, user_id=None, volume_id=None):  # noqa: E501
        """ServerCreateSnapshotFromRun - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._run_id = None
        self._user_id = None
        self._volume_id = None
        self.discriminator = None
        if description is not None:
            self.description = description
        self.run_id = run_id
        self.user_id = user_id
        self.volume_id = volume_id

    @property
    def description(self):
        """Gets the description of this ServerCreateSnapshotFromRun.  # noqa: E501


        :return: The description of this ServerCreateSnapshotFromRun.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ServerCreateSnapshotFromRun.


        :param description: The description of this ServerCreateSnapshotFromRun.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def run_id(self):
        """Gets the run_id of this ServerCreateSnapshotFromRun.  # noqa: E501

        Run ID associated with the snapshot  # noqa: E501

        :return: The run_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this ServerCreateSnapshotFromRun.

        Run ID associated with the snapshot  # noqa: E501

        :param run_id: The run_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :type: str
        """
        if run_id is None:
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501

        self._run_id = run_id

    @property
    def user_id(self):
        """Gets the user_id of this ServerCreateSnapshotFromRun.  # noqa: E501

        User that initiated the run, set as snapshot creator  # noqa: E501

        :return: The user_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this ServerCreateSnapshotFromRun.

        User that initiated the run, set as snapshot creator  # noqa: E501

        :param user_id: The user_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def volume_id(self):
        """Gets the volume_id of this ServerCreateSnapshotFromRun.  # noqa: E501


        :return: The volume_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :rtype: str
        """
        return self._volume_id

    @volume_id.setter
    def volume_id(self, volume_id):
        """Sets the volume_id of this ServerCreateSnapshotFromRun.


        :param volume_id: The volume_id of this ServerCreateSnapshotFromRun.  # noqa: E501
        :type: str
        """
        if volume_id is None:
            raise ValueError("Invalid value for `volume_id`, must not be `None`")  # noqa: E501

        self._volume_id = volume_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ServerCreateSnapshotFromRun, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerCreateSnapshotFromRun):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
