openapi: 3.0.0

info:
  title: FeatureStore API
  description: Feature Store metadata service
  version: 0.1.0

paths:
  /{featureStoreName}:
    post:
      summary: Create FeatureStore
      parameters:
        - in: path
          name: featureStoreName
          required: true
          schema:
            type: string
            minimum: 1
          description: FeatureStore name
      requestBody:
        description: CreateFeatureStoreRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFeatureStoreRequest'
      responses:
        '200':
          description: The new FeatureStore
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureStore'

components:
  schemas:
    FeatureStore:
      type: object
      properties:
        id:
          type: string
        projectId:
          type: string
        name:
          type: string
        creationTime:
          type: string
          format: date-time
        featureViews:
          type: array
          items:
            type: string
      required:
        - id
        - projectId
        - name
        - creationTime
        - featureViews
    FeatureView:
      type: object
      properties:
        name:
          type: string
        ttl:
          type: string
          format: date-time
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        batchSource:
          $ref: '#/components/schemas/BatchSource'
        storeLocation:
          $ref: '#/components/schemas/StoreLocation'
        tags:
          type: object
          additionalProperties:
            type: string
      required:
        - name
        - ttl
        - features
        - batchSource
        - storeLocation
    Feature:
      type: object
      properties:
        name:
          type: string
        valueType:
          type: string
      required:
        - name
        - valueType
    Entity:
      type: object
      properties:
        name:
          type: string
        joinKey:
          type: string
        valueType:
          type: string
      required:
        - name
        - valueType
    BatchSource:
      type: object
      properties:
        dataSource:
          type: string
        eventTimestampColumn:
          type: string
        createdTimestampColumn:
          type: string
        datePartitionColumn:
          type: string
      required:
        - dataSource
        - eventTimestampColumn
        - createdTimestampColumn
        - datePartitionColumn
    StoreLocation:
      type: object
      properties:
        bucket:
          type: string
        region:
          type: string
      required:
        - bucket
        - region
    CreateFeatureStoreRequest:
      type: object
      properties:
        name:
          type: string
        projectId:
          type: string
        featureViews:
          $ref: '#/components/schemas/FeatureView'
      required:
        - name
        - projectId
        - featureViews
