# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.data_transfers_api import DataTransfersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataTransfersApi(unittest.TestCase):
    """DataTransfersApi unit test stubs"""

    def setUp(self):
        self.api = DataTransfersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_transfers_id_callback_post(self):
        """Test case for data_transfers_id_callback_post

        Callback for data transfer from filetask  # noqa: E501
        """
        pass

    def test_data_transfers_id_get(self):
        """Test case for data_transfers_id_get

        Get data transfer by ID  # noqa: E501
        """
        pass

    def test_data_transfers_post(self):
        """Test case for data_transfers_post

        Create new data transfer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
