# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.snapshots_api import SnapshotsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSnapshotsApi(unittest.TestCase):
    """SnapshotsApi unit test stubs"""

    def setUp(self):
        self.api = SnapshotsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rpc_create_snapshot_from_run_post(self):
        """Test case for rpc_create_snapshot_from_run_post

        Create new snapshot from a run  # noqa: E501
        """
        pass

    def test_rpc_delete_snapshot_post(self):
        """Test case for rpc_delete_snapshot_post

        Delete snapshot by ID  # noqa: E501
        """
        pass

    def test_rpc_restore_snapshot_post(self):
        """Test case for rpc_restore_snapshot_post

        Restore snapshot to active state  # noqa: E501
        """
        pass

    def test_snapshots_get(self):
        """Test case for snapshots_get

        List snapshots  # noqa: E501
        """
        pass

    def test_snapshots_id_get(self):
        """Test case for snapshots_id_get

        Get snapshot by ID  # noqa: E501
        """
        pass

    def test_snapshots_id_put(self):
        """Test case for snapshots_id_put

        Update Snapshot by ID  # noqa: E501
        """
        pass

    def test_snapshots_post(self):
        """Test case for snapshots_post

        Create new snapshot  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
