# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.downloads_api import DownloadsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDownloadsApi(unittest.TestCase):
    """DownloadsApi unit test stubs"""

    def setUp(self):
        self.api = DownloadsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_downloads_id_get(self):
        """Test case for downloads_id_get

        Get download task status  # noqa: E501
        """
        pass

    def test_downloads_post(self):
        """Test case for downloads_post

        Create download archive  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
