# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authz_api import AuthzApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthzApi(unittest.TestCase):
    """AuthzApi unit test stubs"""

    def setUp(self):
        self.api = AuthzApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_authz_permissions_authorizedactions_post(self):
        """Test case for account_authz_permissions_authorizedactions_post

        Gets all permissions for requesting user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
