# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.filesystems_api import FilesystemsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFilesystemsApi(unittest.TestCase):
    """FilesystemsApi unit test stubs"""

    def setUp(self):
        self.api = FilesystemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_filesystems_get(self):
        """Test case for filesystems_get

        List filesystem  # noqa: E501
        """
        pass

    def test_filesystems_id_delete(self):
        """Test case for filesystems_id_delete

        Delete filesystem by ID  # noqa: E501
        """
        pass

    def test_filesystems_id_get(self):
        """Test case for filesystems_id_get

        Get filesystem by ID  # noqa: E501
        """
        pass

    def test_filesystems_id_put(self):
        """Test case for filesystems_id_put

        Update filesystem  # noqa: E501
        """
        pass

    def test_filesystems_post(self):
        """Test case for filesystems_post

        Create new filesystem  # noqa: E501
        """
        pass

    def test_root_pvcs_get(self):
        """Test case for root_pvcs_get

        List available PVCs in the domino-compute namespace with the netapp-storage label  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
