# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.remotefs_meta import RemotefsMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestRemotefsMeta(unittest.TestCase):
    """RemotefsMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemotefsMeta(self):
        """Test RemotefsMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.remotefs_meta.RemotefsMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
