# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.server_create_volume_request import ServerCreateVolumeRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestServerCreateVolumeRequest(unittest.TestCase):
    """ServerCreateVolumeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerCreateVolumeRequest(self):
        """Test ServerCreateVolumeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.server_create_volume_request.ServerCreateVolumeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
