# coding: utf-8

"""
    Domino Volumes for NetApp ONTAP Microservice API

    Microservice responsible for managing Domino Volumes for NetApp ONTAP feature  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@dominodatalab.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ServerCreateVolumeRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "capacity": "int",
        "description": "str",
        "filesystem_id": "str",
        "grants": "list[RemotefsVolumeGrantDTO]",
        "name": "str",
        "project_id": "str",
    }

    attribute_map = {
        "capacity": "capacity",
        "description": "description",
        "filesystem_id": "filesystemId",
        "grants": "grants",
        "name": "name",
        "project_id": "projectId",
    }

    def __init__(
        self,
        capacity=None,
        description=None,
        filesystem_id=None,
        grants=None,
        name=None,
        project_id=None,
    ):  # noqa: E501
        """ServerCreateVolumeRequest - a model defined in Swagger"""  # noqa: E501
        self._capacity = None
        self._description = None
        self._filesystem_id = None
        self._grants = None
        self._name = None
        self._project_id = None
        self.discriminator = None
        self.capacity = capacity
        if description is not None:
            self.description = description
        self.filesystem_id = filesystem_id
        self.grants = grants
        self.name = name
        if project_id is not None:
            self.project_id = project_id

    @property
    def capacity(self):
        """Gets the capacity of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The capacity of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this ServerCreateVolumeRequest.


        :param capacity: The capacity of this ServerCreateVolumeRequest.  # noqa: E501
        :type: int
        """
        if capacity is None:
            raise ValueError("Invalid value for `capacity`, must not be `None`")  # noqa: E501

        self._capacity = capacity

    @property
    def description(self):
        """Gets the description of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The description of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ServerCreateVolumeRequest.


        :param description: The description of this ServerCreateVolumeRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def filesystem_id(self):
        """Gets the filesystem_id of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The filesystem_id of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: str
        """
        return self._filesystem_id

    @filesystem_id.setter
    def filesystem_id(self, filesystem_id):
        """Sets the filesystem_id of this ServerCreateVolumeRequest.


        :param filesystem_id: The filesystem_id of this ServerCreateVolumeRequest.  # noqa: E501
        :type: str
        """
        if filesystem_id is None:
            raise ValueError("Invalid value for `filesystem_id`, must not be `None`")  # noqa: E501

        self._filesystem_id = filesystem_id

    @property
    def grants(self):
        """Gets the grants of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The grants of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: list[RemotefsVolumeGrantDTO]
        """
        return self._grants

    @grants.setter
    def grants(self, grants):
        """Sets the grants of this ServerCreateVolumeRequest.


        :param grants: The grants of this ServerCreateVolumeRequest.  # noqa: E501
        :type: list[RemotefsVolumeGrantDTO]
        """
        if grants is None:
            raise ValueError("Invalid value for `grants`, must not be `None`")  # noqa: E501

        self._grants = grants

    @property
    def name(self):
        """Gets the name of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The name of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ServerCreateVolumeRequest.


        :param name: The name of this ServerCreateVolumeRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this ServerCreateVolumeRequest.  # noqa: E501


        :return: The project_id of this ServerCreateVolumeRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ServerCreateVolumeRequest.


        :param project_id: The project_id of this ServerCreateVolumeRequest.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ServerCreateVolumeRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerCreateVolumeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
